include:
  - board: seeeduino_xiao_ble
    shield: settings_reset

  - board: seeeduino_xiao_ble
    shield: my_keyboard_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: seeeduino_xiao_ble
    shield: totem_left  
  - board: seeeduino_xiao_ble
    shield: totem_right 